#!/usr/bin/fish

# path to cloned https://github.com/stefan-hoeck/idris2-pack-docs
set pack_docs /home/dev_grass/workspace/forks/idris2-pack-db-docs

# dir of processed .json files
set index_dir /home/dev_grass/workspace/personal/idris2-docs-indexer-html/processed
set data_dir (dirname (status -f))/data

rm -fr $data_dir/
mkdir $data_dir
rsync -a $pack_docs/docs/ $data_dir/
rsync -a $index_dir/ $data_dir/
scripts/gen-packages-json.py $data_dir/